### ISSUE TITLE
How to get past the NGINX Manager?

### ISSUE THREAD

**Issue by chopfitzroy** [matejkramny/Modern-File-Browser#1]
How to get past the NGINX Manager?

What password / username should I use?

**Comment by matejkramny** [comment]
Hi @CrashyBang. I think you'll have to manually create the first user.

I'll update the code shortly (today, GMT timezone) to create an initial user if none exist.

Thanks for reporting this issue

**Comment by matejkramny** [comment]
Fixed with commit 55f90d3ac0c1e07053399c7ab806826ede033f19
